/**
 * Build-time generation of the standalone Ajv validators (dossier 5.1, ADR-0027).
 *
 * This is the only place allowed to import Ajv. The generated module is a plain ES module with no
 * import, no `require` and no dynamic code evaluation, so it runs under a CSP without
 * `unsafe-eval`. Ajv itself never reaches the shipped applications.
 */
import type { TSchema } from '@sinclair/typebox';
import { Ajv } from 'ajv';
import standaloneCode from 'ajv/dist/standalone';
import { mkdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

export type SchemaRegistry = Readonly<Record<string, TSchema>>;

export type GeneratedValidators = { readonly js: string; readonly dts: string };

const HEADER = '// Generated by scripts/generate-validators.ts. Do not edit.\n';

/** Ajv still announces that `unicode: false` is deprecated; that choice is deliberate (ADR-0027). */
const EXPECTED_WARNING = /option unicode/;

/** Patterns that would make the output depend on something at run time. */
const FORBIDDEN_IN_OUTPUT: readonly [RegExp, string][] = [
  [/require\s*\(/, 'a require() call'],
  [/(^|[;\n])\s*import\s/, 'an import statement'],
  [/new\s+Function\b/, 'new Function'],
  [/\beval\s*\(/, 'eval'],
];

export function validatorName(schemaName: string): string {
  return `validate${schemaName}`;
}

export function generateValidators(schemas: SchemaRegistry): GeneratedValidators {
  const unexpected: string[] = [];
  const ajv = new Ajv({
    code: { source: true, esm: true },
    allErrors: true,
    strict: true,
    discriminator: true,
    // Length of strings in UTF-16 units: avoids Ajv's `require("ajv/dist/runtime/ucs2length")`.
    unicode: false,
    logger: {
      log: () => undefined,
      warn: (message: unknown) => {
        if (!EXPECTED_WARNING.test(String(message))) unexpected.push(String(message));
      },
      error: (message: unknown) => {
        unexpected.push(String(message));
      },
    },
  });

  const exportsMap: Record<string, string> = {};
  for (const [name, schema] of Object.entries(schemas)) {
    ajv.addSchema(schema, name);
    exportsMap[validatorName(name)] = name;
  }
  const code = HEADER + standaloneCode(ajv, exportsMap);

  if (unexpected.length > 0) {
    throw new Error(`Ajv reported warnings during generation:\n${unexpected.join('\n')}`);
  }
  for (const [pattern, what] of FORBIDDEN_IN_OUTPUT) {
    if (pattern.test(code)) {
      throw new Error(`Generated validators are not self-contained: they contain ${what}.`);
    }
  }
  return { js: code, dts: declarationsFor(Object.keys(schemas)) };
}

function declarationsFor(names: readonly string[]): string {
  const lines = [
    HEADER.trimEnd(),
    'export interface ValidationErrorLike {',
    '  readonly instancePath: string;',
    '  readonly schemaPath: string;',
    '  readonly keyword: string;',
    '  readonly params: Readonly<Record<string, unknown>>;',
    '  readonly message?: string;',
    '}',
    'export interface ValidatorFunction {',
    '  (data: unknown): boolean;',
    '  errors?: ReadonlyArray<ValidationErrorLike> | null;',
    '}',
    ...names.map((name) => `export const ${validatorName(name)}: ValidatorFunction;`),
  ];
  return `${lines.join('\n')}\n`;
}

/** Writes `validators.js` and `validators.d.ts` into `directory`. */
export function writeValidators(directory: string, schemas: SchemaRegistry): GeneratedValidators {
  const generated = generateValidators(schemas);
  mkdirSync(directory, { recursive: true });
  writeFileSync(join(directory, 'validators.js'), generated.js);
  writeFileSync(join(directory, 'validators.d.ts'), generated.dts);
  return generated;
}
